name = "schrimpf"
uuid = "bfa01b86-6834-4d9d-9b5e-d279d1a58764"
repo = "git@github.com:schrimpf/juliaregistry"
description = "Packages for teaching"

[packages]
9b71aec8-1451-11e9-12ed-579ec60579c4 = { name = "Dialysis", path = "D/Dialysis" }
